return {
  -- disable trouble
  { "folke/noice.nvim", enabled = false },
  { "rcarriga/nvim-notify", enabled = false },
  -- { "stevearc/conform.nvim", enabled = false },
  { "mfussenegger/nvim-lint", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "echasnovski/mini.pairs", enabled = false },
  { "echasnovski/mini.animate", enabled = false },
  { "RRethy/vim-illuminate", enabled = false },
  { "folke/todo-comments.nvim", enabled = false },
  { "echasnovski/mini.indentscope", enabled = false },
  -- { "nvim-treesitter/nvim-treesitter-context", enabled = false },
  -- { "Bekaboo/dropbar.nvim", enabled = false },
  -- { "lukas-reineke/indent-blankline.nvim", enabled = false },
  -- { "hrsh7th/nvim-cmp", enabled = false },
  { "ms-jpq/coq_nvim", enabled = false },
  -- { "ray-x/lsp_signature.nvim", enabled = false },
  { "bufferline.nvim", enabled = false},
  { "ranjithshegde/ccls.nvim", enabled = false},
  { "AlejandroSuero/freeze-code.nvim", enabled = false},
}
